# <font color='red'>Linear Regression Multiple Variables</font>


## Question
**Sample problem of predicting home price in monroe, new jersey (USA)** <br>
Below is the table containing home prices in monroe twp, NJ. Here price depends on area (square feet), bed rooms and age of the home (in years). Given these prices we have to predict prices of new homes based on area, bed rooms and age.
<img src='homeprices.jpg'><br>
**Given these home prices find out price of a home that has, <br>
a. 3000 sqr ft area, 3 bedrooms, 40 year old ,<br>
b. 2500 sqr ft area, 4 bedrooms, 5 year old** <br><br>

We will use regression with multiple variables here. Price can be calculated using following equation,<br>
<img src='home_equation.jpg'> <br>
<img src='general_equation.jpg'>
<br><br><br>
# <font color='red'>Solution</font>

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model as lm

In [3]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
df.bedrooms.median()

4.0

In [6]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
reg = lm.LinearRegression()  # reg = regression model
reg.fit(df[['area', 'bedrooms', 'age']], df.price)    # reg.fit(df[[independent variables of the df]], target_variable)

LinearRegression()

### Ans to the question no (a)

In [12]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

### Ans to the question no (b)

In [14]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

## <font color='red'>Manual Process</font>

In [15]:
# Value of Coefficient m1, m2 and m3
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
# Value of Intercept
reg.intercept_

221323.00186540443

**Answer(a)**

In [24]:
Price2 = 112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540443
Price2

498408.25157402444

**Answer(b)**

In [25]:
Price = 112.06244194*2500 + 23388.88007794*4 + -3231.71790863*5 + 221323.00186540443
Price

578876.0374840144