# <font color='red'>K-Fold_CrossValidation
    
<img src='13-1.png'>
<img src='13-2.png'>
<img src='13-3.png'>
<img src='13-4.png'>
<img src='13-5.png'>
<img src='13-6.png'>
<img src='13-7.png'>
<img src='13-8.png'>
<img src='13-9.png'>

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import numpy as np

digits = load_digits()

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [60]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\MD GOLAM RABBANI\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [61]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [62]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9685185185185186

In [63]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [64]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [65]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

### For Logistic Regression

In [66]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

C:\Users\MD GOLAM RABBANI\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

### For Random Forest Classifier

In [67]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9722222222222222

### For Support Vector Machine (SVM)

In [68]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9888888888888889

In [69]:
from sklearn.model_selection import StratifiedKFold
flod = StratifiedKFold(n_splits=3)

In [82]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index],digits.target[train_index],\
                                       digits.target[test_index]
    
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

C:\Users\MD GOLAM RABBANI\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\MD GOLAM RABBANI\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

In [83]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [84]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [85]:
scores_rf

[0.9265442404006677, 0.9449081803005008, 0.9232053422370617]

### Uning Library function

In [86]:
from sklearn.model_selection import cross_val_score

In [87]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\MD GOLAM RABBANI\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\MD GOLAM RABBANI\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stab

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [88]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [90]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.91388889, 0.90277778, 0.95821727, 0.96657382, 0.91364903])

In [91]:
cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target)

array([0.88333333, 0.86944444, 0.93036212, 0.95264624, 0.87465181])

In [92]:
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target)

array([0.92777778, 0.86388889, 0.95264624, 0.94428969, 0.91364903])

In [93]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target)

array([0.91388889, 0.89444444, 0.95264624, 0.96657382, 0.91643454])