# <font color='red'>Save Model Using Joblib And Pickle</font>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model as lm

In [2]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [30]:
reg_model = lm.LinearRegression()
reg_model.fit(df[['area']], df.price)

LinearRegression()

In [31]:
reg_model.predict([[2600]])

array([533664.38356164])

In [32]:
reg_model.predict([[5000]])

array([859554.79452055])

In [33]:
reg_model.coef_

array([135.78767123])

In [34]:
reg_model.intercept_

180616.43835616432

In [42]:
price = reg_model.coef_*5000+reg_model.intercept_
price

array([859554.79452055])

### Save the above Trained-up Model Using  Pickle and Joblib


#### Pickle

In [43]:
import pickle

In [44]:
with open('my_model','wb') as file:
    pickle.dump(reg_model,file)

In [45]:
with open('my_model','rb') as file:
    mp = pickle.load(file)

In [46]:
mp.predict([[5000]])

array([859554.79452055])

#### Joblib

#### Note:
In the specific case of scikit-learn, it may be better to use joblib’s replacement of pickle (dump & load), which is more efficient on objects that carry large numpy arrays internally as is often the case for fitted scikit-learn estimators, but can only pickle to the disk and not to a string

Usually people says joblib is more efficient when a lot number of numpy array is used in a model


In [58]:
import joblib

In [64]:
joblib.dump(reg_model, 'mymodel_joblib')

['mymodel_joblib']

In [65]:
mj = joblib.load('mymodel_joblib')

In [66]:
mj.predict([[5000]])

array([859554.79452055])

In [67]:
mj.coef_

array([135.78767123])

In [68]:
mj.intercept_

180616.43835616432